apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8scrud
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8scrud
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8scrud
  namespace: default
subjects:
  - kind: ServiceAccount
    name: k8scrud
roleRef:
  kind: Role
  name: k8scrud
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8scrud
  name: k8scrud
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8scrud
  strategy: {}
  template:
    metadata:
      labels:
        app: k8scrud
    spec:
      serviceAccountName: k8scrud
      imagePullSecrets:
        - name: gitlabregistrykey
      containers:
        - image: registry.sweetmemoryalbums.com/k8scrud:latest
          name: k8scrud
          env:
            - name: "k8scrud.yamldir"
              value: "/"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8scrud
  name: k8scrud
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: k8scrud
  type: ClusterIP

