{{- if .Values.serviceAccount.useClusterAdminRole -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8scrud.serviceAccountName" . }}
  labels:
        {{- include "k8scrud.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8scrud.serviceAccountName" . }}
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: "cluster-admin"
  apiGroup: rbac.authorization.k8s.io
{{- end }}