apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "k8scrud.namespace" . | nindent 2 }}
  name: {{ include "k8scrud.fullname" . }}
  labels:
    {{- include "k8scrud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8scrud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "k8scrud.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8scrud.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - image: fritzduchardt/nginx-environment-configurator:latest
          name: nginx-environment-configurator
          volumeMounts:
            - name: nginx-conf
              mountPath: "/work-dir"
          env:
            - name: NGINX_CONFIG_PATH
              value: "/work-dir/default.conf"
            - name: LOCATION_1
              value: "/"
            - name: PROXYPASS_1
              value: "http://localhost:8080/"
            - name: LOCATION_2
              value: "/swagger"
            - name: PROXYPASS_2
              value: "http://localhost:8081/"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
          volumeMounts:
          - mountPath: /k8scrud-manifests
            name: k8scrud-manifests
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - image: swaggerapi/swagger-ui:latest
          imagePullPolicy: IfNotPresent
          name: swaggerapi
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: PORT
              value: "8081"
            - name: SWAGGER_JSON_URL
              value: http://localhost:8080/v2/api-docs
        - image: nginx:latest
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: nginx-conf
      volumes:
        - name: nginx-conf
          emptyDir: {}
        - name: k8scrud-manifests
          configMap:
            name: k8scrud-manifests
            optional: true
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ .Chart.Name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
