apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ include "k8scrud.fullname" . }}
    namespace: kube-system
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 1078Mi