apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: k8scrud
    {{- include "k8scrud.namespace" . | nindent 4 }}
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 1078Mi