{{- if not (.Values.serviceAccount.useClusterAdminRole) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  {{- include "k8scrud.namespace" . | nindent 2 }}
  name: {{ include "k8scrud.serviceAccountName" . }}
  labels:
      {{- include "k8scrud.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
{{- end }}