apiVersion: v1
kind: Service
metadata:
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  {{- include "k8scrud.namespace" . | nindent 2 }}
  name: {{ include "k8scrud.fullname" . }}
  labels:
    {{- include "k8scrud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "k8scrud.selectorLabels" . | nindent 4 }}
