version: 2.1

orbs:
  kube-orb: circleci/kubernetes@0.11.0

jobs:

  build:
    docker:
      - image: openjdk:11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: gradle-dependencies-{{ checksum "build.gradle" }}
      - run: |
          ./gradlew bootJar
          mv build/libs/k8scrud*jar build/libs/k8scrud.jar
      - persist_to_workspace:
          root: build
          paths:
            - libs/*.jar
      - save_cache:
          key: gradle-dependencies-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

  publish-docker-image:
    docker:
      - image: docker
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: build
      - run: |
          VERSION=$(cat gradle.properties | grep -oE '\d+\.\d+.\d+')
          docker login -u fritzduchardt -p $DOCKER_HUB_PASSWORD
          docker build -f Dockerfile-singlestage -t fritzduchardt/k8scrud:latest .
          docker tag fritzduchardt/k8scrud:latest fritzduchardt/k8scrud:$VERSION
          docker push fritzduchardt/k8scrud:$VERSION
          docker push fritzduchardt/k8scrud:latest

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat gradle.properties | grep -oE '\d+\.\d+.\d+')
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/libs

  release-new-version:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          gradle release -Prelease.useAutomaticVersion=true

  deploy-to-k8s:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/repo
    steps:
      - checkout
      - kube-orb/install:
          kubectl-version: v1.15.2
      - kube-orb/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - run: |
          kubectl apply -f src/main/k8s-manifest/deploy-to-default-namespace.yaml

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
      - publish-docker-image:
          requires:
            - build
      - deploy-to-k8s:
          requires:
            - build
      - release-new-version:
          requires:
            - publish-github-release
            - publish-docker-image
            - deploy-to-k8s
