version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.11.0
jobs:
  build:
    docker: true
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login registry.sweetmemoryalbums.com/ -u admin -p $GITLAB_PASSWORD
          docker build -t registry.sweetmemoryalbums.com/k8scrud:latest .
          docker push registry.sweetmemoryalbums.com/k8scrud:latest

  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - kube-orb/install-kubectl
      - kube-orb/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deploy-to-k8s.yaml
          show-kubectl-command: true