version: 2.1

orbs:
  kube-orb: circleci/kubernetes@0.11.0

jobs:
  build:
    docker:
      - image: docker
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u fritzduchardt -p $DOCKER_HUB_PASSWORD
          docker build -t fritzduchardt/k8scrud:$VERSION .
          docker tag fritzduchardt/k8scrud:latest fritzduchardt/k8scrud:$VERSION
          docker push fritzduchardt/k8scrud:$VERSION
          docker push fritzduchardt/k8scrud:latest

  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - kube-orb/install:
          kubectl-version: v1.15.2
      - kube-orb/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - run: |
          kubectl apply -f deploy/manifest/deploy-to-default-namespace.yaml

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
