version: 2.1

orbs:
  kube-orb: circleci/kubernetes@0.11.0

jobs:
  build:
    docker:
      # any circle ci convenience image will do
      - image: 'circleci/golang:latest'
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          LAST_RELEASE=$(curl --silent "https://api.github.com/repos/fritzduchardt/k8scrud/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
          docker login -u fritzduchardt -p $DOCKER_HUB_PASSWORD
          docker build -t fritzduchardt/k8scrud:LAST_RELEASE .
          docker tag fritzduchardt/k8scrud:latest fritzduchardt/k8scrud:LAST_RELEASE
          docker push fritzduchardt/k8scrud:LAST_RELEASE
          docker push fritzduchardt/k8scrud:latest

  deploy:
    docker:
      - image: 'circleci/golang:latest'
    steps:
      - checkout
      - kube-orb/install:
          kubectl-version: v1.15.2
      - kube-orb/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - run: |
          kubectl apply -f deploy/manifest/deploy-to-default-namespace.yaml

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
