version: 2.1

orbs:
  kube-orb: circleci/kubernetes@0.11.0

jobs:

  build:
    docker:
      - image: openjdk:11
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          ./gradlew bootJar
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - build/libs

  publish-docker-image:
    docker:
      - image: docker
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          LAST_RELEASE=$(curl --silent "https://api.github.com/repos/fritzduchardt/k8scrud/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
          docker login -u fritzduchardt -p $DOCKER_HUB_PASSWORD
          docker build -t fritzduchardt/k8scrud:LAST_RELEASE .
          docker tag fritzduchardt/k8scrud:latest fritzduchardt/k8scrud:LAST_RELEASE
          docker push fritzduchardt/k8scrud:LAST_RELEASE
          docker push fritzduchardt/k8scrud:latest

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=0.0.2
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/libs

  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - kube-orb/install:
          kubectl-version: v1.15.2
      - kube-orb/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - run: |
          kubectl apply -f deploy/manifest/deploy-to-default-namespace.yaml

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
#      - publish-docker-image
      - build
      - publish-github-release:
          requires:
            - build
#      - deploy:
#          requires:
#            - build
