version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.11.0
jobs:
  build:
    docker:
      - image: docker
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login registry.sweetmemoryalbums.com/ -u admin -p $GITLAB_PASSWORD
          docker build -t registry.sweetmemoryalbums.com/k8scrud:latest .
          docker push registry.sweetmemoryalbums.com/k8scrud:latest

  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - kube-orb/install:
          kubectl-version: v1.15.2
      - run: |
          kubectl version

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy