{{- if .Values.serviceAccount.useClusterAdminRole -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "kube-system"
  name: {{ include "k8scrud.serviceAccountName" . }}
  labels:
    {{- include "k8scrud.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- else }}
{{- end }}