{{- if not (.Values.serviceAccount.useClusterAdminRole) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "k8scrud.namespace" . | nindent 2 }}
  name: {{ include "k8scrud.serviceAccountName" . }}
  labels:
    {{- include "k8scrud.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- else }}
{{- end }}