apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-{{ .K8scrud.id }}
    app.kubernetes.io/name: k8scrud-example-nginx
  name: nginx-{{ .K8scrud.id }}
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-{{ .K8scrud.id }}
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-{{ .K8scrud.id }}
        app.kubernetes.io/name: k8scrud-example-nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          env:
            - name: CUSTOM_ENV
              value: {{ .K8scrud.params.yourEnvValue }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-{{ .K8scrud.id }}
    app.kubernetes.io/name: k8scrud-example-nginx
  name: nginx-{{ .K8scrud.id }}
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-{{ .K8scrud.id }}
  type: ClusterIP