apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-{{ .K8scrud.id }}
  name: nginx-{{ .K8scrud.id }}
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-{{ .K8scrud.id }}
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-{{ .K8scrud.id }}
    spec:
      containers:
        - image: nginx
          name: nginx
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-{{ .K8scrud.id }}
  name: nginx-{{ .K8scrud.id }}
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-{{ .K8scrud.id }}
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: nginx-{{ .K8scrud.id }}
  namespace: default
spec:
  rules:
    - http:
        paths:
          - path: /{{ .K8scrud.id }}
            backend:
              serviceName: nginx-{{ .K8scrud.id }}
              servicePort: 8080
