apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8scrud
  namespace: kube-system
  labels:
    app.kubernetes.io/name: k8scrud
    app.kubernetes.io/instance: k8scrud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8scrud
  namespace: kube-system
  labels:
    app.kubernetes.io/name: k8scrud
    app.kubernetes.io/instance: k8scrud
subjects:
  - kind: ServiceAccount
    name: k8scrud
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: k8scrud
    app.kubernetes.io/instance: k8scrud
  name: k8scrud
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8scrud
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8scrud
        app.kubernetes.io/instance: k8scrud
    spec:
      serviceAccountName: k8scrud
      containers:
        - image: fritzduchardt/k8scrud:b40b03509dc32a8b7c34a831c0659074a67f341a
          imagePullPolicy: Always
          name: k8scrud
          env:
            - name: "k8scrud.yamldir"
              value: "/"
          volumeMounts:
            - mountPath: /k8s-manifests
              name: k8s-manifests
      volumes:
        - name: k8s-manifests
          persistentVolumeClaim:
            claimName: k8scrud
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: k8scrud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8scrud
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1078Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: k8scrud
    app.kubernetes.io/instance: k8scrud
  name: k8scrud
  namespace: kube-system
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: k8scrud
  type: ClusterIP

