apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8scrud
  namespace: kube-system
  labels:
    app.kubernetes.io/name: k8scrud
    app.kubernetes.io/instance: k8scrud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8scrud
  namespace: kube-system
  labels:
    app.kubernetes.io/name: k8scrud
    app.kubernetes.io/instance: k8scrud
subjects:
  - kind: ServiceAccount
    name: k8scrud
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: k8scrud
    app.kubernetes.io/instance: k8scrud
  name: k8scrud
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8scrud
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8scrud
        app.kubernetes.io/instance: k8scrud
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /prometheus
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: k8scrud
      containers:
        - image: fritzduchardt/k8scrud:latest
          imagePullPolicy: Always
          name: k8scrud
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
          volumeMounts:
            - mountPath: /k8scrud-manifests
              name: k8scrud-manifests
      volumes:
        - name: k8scrud-manifests
          persistentVolumeClaim:
            claimName: k8scrud
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: k8scrud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8scrud
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1078Mi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /prometheus
    prometheus.io/port: "9090"
  labels:
    app.kubernetes.io/name: k8scrud
    app.kubernetes.io/instance: k8scrud
  name: k8scrud
  namespace: kube-system
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: k8scrud
  type: ClusterIP

